spring:
  datasource:
    url: jdbc:postgresql://trolley.proxy.rlwy.net:51055/railway?sslmode=require&stringtype=unspecified&characterEncoding=UTF-8
    username: postgres
    password: UwiUOreOefKFWDimKjNMkiqAQeQxUzHL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

deepseek:
  apiKey: ${DEEPSEEK_APIKEY:}

logging:
  level:
    com:
      example:
        repository: DEBUG
        controller: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    com.example.service: DEBUG


server:
  port: ${PORT:8081}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true